version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://appuser:secretpassword@database:5432/hotelbooking
      - REDIS_URL=redis://redis:6379
      - SUNHOTELS_API_KEY=${SUNHOTELS_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
      - redis
    restart: unless-stopped

  database:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_DB=hotelbooking
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  postgres_
